production:
  adapter: redis
  url: redis://https://my-jira-heroku.herokuapp.com/1
  channel_prefix: my_jira_production

test:
  adapter: async

development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: my_jira_development
